server:
  port: 9001
  
cloud:
  aws:
    credentials:
      access-key: accesskey
      secret-key: secrekKey
    region:
      auto: false
      static: us-east-1
    end-point: 
      uri: https://sqs.us-east-1.amazonaws.com/55555555555/QUEUE_TEST2
    stack:
      auto: false